# Generated by Django 2.0.2 on 2019-10-17 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='arquivo',
            name='notas',
            field=models.FloatField(default=None),
        ),
    ]
